version: '3'
services:
  # cli:
  #   image: nestjs/cli
  #   working_dir: /workspace
  #   volumes:
  #     - .:/workspace
  #   tty: true
  # node:
  #   image: node:${NODE_VERSION}
  #   working_dir: /workspace
  #   ports:
  #     - ${APP_PORT}:3000
  #   expose:
  #     - '3000'
  #   networks:
  #     - bridge
  #   # command: apk add build-base python gcc g++
  #   tty: true
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    privileged: true
    environment:
      MYSQL_DATABASE: nestjs
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'
networks:
  bridge:
    driver: bridge
